### ISSUE TITLE
is_available 작성

### ISSUE THREAD

**Issue by GhoRid** [jnu-project-2team/numbaseball-2team#1]
## Description

is_available 함수를 작성합니다.

## Tasks

- [] error_code 0
- [] error_code 1 (길이 검사)
- [] error_code 2 (중복 검사)
- [] error_code 3 (is_digit 검사)
