### ISSUE TITLE
try_answer 작성

### ISSUE THREAD

**Issue by vi-wolhwa** [jnu-project-2team/numbaseball-2team#2]
## Description
사용자의 정답을 입력받고, 결과를 출력하는 함수

## Tasks
- [x] 사용자 정답 입력
- [x] 사용자 입력 유효성 테스트
- [x] 결과 출력
- [ ] 출력 포맷 수정
